// generated by kwalify from servicemapping.schema.yml
package com.netapp.glue.conf;
import java.util.*;

/**
 *  Autogenerated binding for the service mapping class
 */
public class ServiceMapping {

    private String _WFAWorkflow;
    private String _StorageServiceName;
    private int _StorageServiceId;
    private String _Description;
    private boolean _IsDRCapable;
    private String _ServiceContact;
    private String _ProtectionPolicy;
    private String _ProtectionPolicyId;
    private List _StorageServiceNodes;

    public ServiceMapping() {}

    public ServiceMapping(Map map) {
        _WFAWorkflow  = (String)map.get("WFAWorkflow");
        _StorageServiceName = (String)map.get("StorageServiceName");
        if (map.get("StorageServiceId") != null) {
            _StorageServiceId = ((Number)map.get("StorageServiceId")).intValue();
        }
        _Description  = (String)map.get("Description");
        if (map.get("IsDRCapable") != null) {
            _IsDRCapable = ((Boolean)map.get("IsDRCapable")).booleanValue();
        }
        _ServiceContact = (String)map.get("ServiceContact");
        _ProtectionPolicy = (String)map.get("ProtectionPolicy");
        _ProtectionPolicyId = (String)map.get("ProtectionPolicyId");
        _StorageServiceNodes = (List)map.get("StorageServiceNodes");
    }

    public String getWfaworkflow() { return _WFAWorkflow; }
    public void setWfaworkflow(String WFAWorkflow_) { _WFAWorkflow = WFAWorkflow_; }
    public String getStorageservicename() { return _StorageServiceName; }
    public void setStorageservicename(String StorageServiceName_) { _StorageServiceName = StorageServiceName_; }
    public int getStorageserviceid() { return _StorageServiceId; }
    public void setStorageserviceid(int StorageServiceId_) { _StorageServiceId = StorageServiceId_; }
    public String getDescription() { return _Description; }
    public void setDescription(String Description_) { _Description = Description_; }
    public boolean isIsdrcapable() { return _IsDRCapable; }
    public void setIsdrcapable(boolean IsDRCapable_) { _IsDRCapable = IsDRCapable_; }
    public String getServicecontact() { return _ServiceContact; }
    public void setServicecontact(String ServiceContact_) { _ServiceContact = ServiceContact_; }
    public String getProtectionpolicy() { return _ProtectionPolicy; }
    public void setProtectionpolicy(String ProtectionPolicy_) { _ProtectionPolicy = ProtectionPolicy_; }
    public String getProtectionpolicyid() { return _ProtectionPolicyId; }
    public void setProtectionpolicyid(String ProtectionPolicyId_) { _ProtectionPolicyId = ProtectionPolicyId_; }
    public List getStorageservicenodes() { return _StorageServiceNodes; }
    public void setStorageservicenodes(List StorageServiceNodes_) { _StorageServiceNodes = StorageServiceNodes_; }
}
