package com.netapp.wfa.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-09T12:12:34.245+05:30
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "WorkflowService", 
                  wsdlLocation = "wfa.wsdl",
                  targetNamespace = "http://ws.wfa.netapp.com/") 
public class WorkflowService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.wfa.netapp.com/", "WorkflowService");
    public final static QName WorkflowServiceDocPort = new QName("http://ws.wfa.netapp.com/", "WorkflowService_docPort");
    static {
        URL url = null;
        try {
            url = new URL("wfa.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WorkflowService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "wfa.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WorkflowService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WorkflowService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkflowService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
//    public WorkflowService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public WorkflowService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
//    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
//    //compliant code instead.
//    public WorkflowService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     *
     * @return
     *     returns WorkflowServiceDoc
     */
    @WebEndpoint(name = "WorkflowService_docPort")
    public WorkflowServiceDoc getWorkflowServiceDocPort() {
        return super.getPort(WorkflowServiceDocPort, WorkflowServiceDoc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkflowServiceDoc
     */
    @WebEndpoint(name = "WorkflowService_docPort")
    public WorkflowServiceDoc getWorkflowServiceDocPort(WebServiceFeature... features) {
        return super.getPort(WorkflowServiceDocPort, WorkflowServiceDoc.class, features);
    }

}
